name: azureml-mlflow-env
channels:
- conda-forge
- defaults
dependencies:
- python=3.11
- pip
- pip:
  - azure-ai-ml==1.11.1
  - azure-identity==1.15.0
  - mlflow==2.8.0
  - azureml-mlflow==1.53.0
  - ipykernel
  - numpy==1.26.1
  - pandas==2.1.2
  - scikit-learn==1.3.2
  - lightgbm==4.1.0
  - xlrd